### ISSUE TITLE
Walnut Sign Drops From Oak Sign

### ISSUE THREAD

**Issue by LunaFabula** [Heccology/Bountiful-Cuisine#38]
I just discovered that you've made it so that an Oak Sign turns into a Walnut Sign when the sign is broken. This, I believe, is an error.

PS: This is related to the loot_tables, you've got the Oak Sign dropping as Walnut Sign.... 

Edit: Also, the problem occurs for Hanging Signs as well.

**Comment by Hecco56** [comment]
unfortunately this issue is only on 1.20.4 (maybe 1.20.2 as well), and I am not updating those versions anymore.

**Comment by LunaFabula** [comment]
Aww, darn it.... Okay.
